// <auto-generated />
namespace InvoiceApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddInvoiceDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInvoiceDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201608250659444_AddInvoiceDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
